name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Display first message
      - name: Display Message 1
        run: echo "Hello, here is message 1!"

      # Display second message
      - name: Display Message 2
        run: echo "Hello, here is message 2!"
